/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Convert Markdown source into a Leaflet document JSON object.
 *
 * # Errors
 * Returns a JS Error if parsing or lens application fails.
 */
export declare function markdownToLeaflet(source: string): any
